# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('descricao_detalhada', models.CharField(max_length=300)),
                ('ano_inicio', models.DateField()),
                ('ano_final', models.DateField()),
            ],
        ),
    ]
