# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_auto_20170514_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compartilhamento',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='compartilhamento',
            name='tarefa',
        ),
        migrations.RemoveField(
            model_name='compartilhamento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Compartilhamento',
        ),
    ]
