# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=1000)),
                ('ano_inicio', models.IntegerField()),
                ('ano_final', models.IntegerField()),
            ],
        ),
    ]
