# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20170428_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='password',
            field=models.CharField(help_text='Use \'[algo]$[salt]$[hexdigest]\' or use the <a href="password/">change password form</a>.', max_length=128),
        ),
    ]
